name: first_desktop_application
description: Hands on With Desktop application.

version: 0.1.0

environment:
  sdk: ">=2.5.2 <3.0.0"

  flutter: ">=1.10.2-pre.54"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.1.0+1

  flare_flutter: ^1.7.3
  intl: ^0.16.1

  get_it: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Bold.otf
        - asset: fonts/Merriweather-Black.otf
